### ISSUE TITLE
[Feature request] Replace command for values?

### ISSUE THREAD

**Issue by PeterCodar** [dbohdan/initool#18] opened 2024-06-01 11:21 UTC
Great tool, thank you @dbohdan 

Could you please add a new command like "replace"?

It would be great to have something that would
a) search for a specific key in a specifc section
and
b) replace the found value A with a new value B

Something like
`initool replace MyTest.ini Section Key OldValue NewValue`

This would be much easier then first check if this value exists and if yes set the NewValue accordingly

**Comment by dbohdan** [comment] 2024-06-02 16:35
> Great tool, thank you @dbohdan

You're welcome!

> Could you please add a new command like "replace"?

> Something like
> `initool replace MyTest.ini Section Key OldValue NewValue`

I like the idea. I have implemented a preliminary version in 1565c5f19a4a31c3592d564adbd2bb97e70880e5. Please try it and tell me what you think. You can download a binary from https://github.com/dbohdan/initool/actions/runs/9339662639.

**Comment by dbohdan** [comment] 2024-06-09 09:19
@PeterCodar Do you have any feedback? If you see no issues, I am going to merge this and release a new version of initool soon.

**Comment by PeterCodar** [comment] 2024-06-09 11:21
Ups sorry.
Somehow I didn't got any information about your preliminary version.
I try it immediately and give you feedback.

**Comment by PeterCodar** [comment] 2024-06-09 11:39
In my first test, I can get it working unfortunately.

I tried it successfully with **get**
```
C:\Temp\initool replace test>initool.exe get test.ini #3 custom_values
[#3]
custom_values=AUDIO\u000bVIDEO\u000bMUSIC\u000bTEXT
```
But with 
`C:\Temp\initool replace test>initool.exe replace test.ini #3 custom_values VIDEO ABC`
I only get listed the entire content of the test.ini
The value VIDEO will not be replaced with ABC.

What should I use as syntax to replace the word VIDEO with the example word ABC?

**Comment by dbohdan** [comment] 2024-06-09 13:47
I think you are trying to replace part of the value, which the command can't do. The way `replace` is currently implemented, it replaces whole values. This is how I understood your request:

> b) replace the found value A with a new value B

But maybe I should look into making it work with string fragments or regular expressions.

**Comment by dbohdan** [comment] 2024-06-09 13:57
I am going to experiment with [sml-regexp](https://github.com/diku-dk/sml-regexp) and get back to you.

**Comment by dbohdan** [comment] 2024-06-09 18:37
It looks like using sml-regexp would be a problem, since it lacks case-insensitive matching. I have implemented simple text replacement in https://github.com/dbohdan/initool/actions/runs/9438439511. Please try it.

**Comment by PeterCodar** [comment] 2024-06-09 18:47
No success.
A simple replace in my test.ini for
```
[#3]
enabled=1
```
with 
`initool.exe replace test.ini #3 enabled 1 5`

does not work (does not replace the value 1 with the new value 5)

**Comment by dbohdan** [comment] 2024-06-10 07:55
I cannot replicate this problem on Windows 10. Could you post a full console transcript that includes your commands and the output from initool?

Here is how [actions/runs/9438439511/artifacts/1583325252](https://github.com/dbohdan/initool/actions/runs/9438439511/artifacts/1583325252) works for me.

## `cmd.exe` 

```none
User@VM F:\initool               
$ type test.ini                               
[#3]                                          
enabled=1                                     
User@VM F:\initool               
$ initool.exe get test.ini                    
[#3]                                          
enabled=1                                     
                                              
User@VM F:\initool               
$ initool.exe replace test.ini #3 enabled 1 5 
[#3]                                          
enabled=5                                     
```

## PowerShell

In PowerShell you must quote the `#`.

```none
PS F:\initool> type test.ini
[#3]
enabled=1
PS F:\initool> .\initool.exe get test.ini
[#3]
enabled=1
PS F:\initool> .\initool.exe replace test.ini #3 enabled 1 5
invalid usage: replace test.ini
usage: replace <filename> <section> <key> <text> <replacement>
PS F:\initool> .\initool.exe replace test.ini '#3' enabled 1 5
[#3]
enabled=5
```

**Comment by PeterCodar** [comment] 2024-06-10 08:12
```
Microsoft Windows [Version 10.0.19045.4412]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Temp\initool replace test>initool.exe get test.ini #3
[#3]
value=Category
size=12
enabled=1
default=\u000b1
multiline=0
prefer_tag=0
version=1

```

`C:\Temp\initool replace test>initool.exe replace test.ini #3 enabled 1 5
`...
the entire content of test.ini will outputted
...

```

C:\Temp\initool replace test>initool.exe get test.ini #3
[#3]
value=Category
size=12
enabled=1
default=\u000b1
multiline=0
prefer_tag=0
version=1
```

**If I reduce the content of my test.ini to the section `#3`, the replace command seems to work fine.**
So I assume, some other entries in the same test.ini prevents the successfull replacement. 

Do you have any limit in INI size or number of sections or number of values?
Or could some special characters as content in the values be the cause?

**Comment by PeterCodar** [comment] 2024-06-10 08:14
You could try to test it with this additional huge example section:

```
[#11]
name=Time (24 hr.) Start (Ex: hh:mm)
value=Start Time
size=6
enabled=1
default=\u000b1
multiline=0
custom_values=00:00\u000b00:01\u000b00:02\u000b00:03\u000b00:04\u000b00:05\u000b00:06\u000b00:07\u000b00:08\u000b00:09\u000b00:10\u000b00:11\u000b00:12\u000b00:13\u000b00:14\u000b00:15\u000b00:16\u000b00:17\u000b00:18\u000b00:19\u000b00:20\u000b00:21\u000b00:22\u000b00:23\u000b00:24\u000b00:25\u000b00:26\u000b00:27\u000b00:28\u000b00:29\u000b00:30\u000b00:31\u000b00:32\u000b00:33\u000b00:34\u000b00:35\u000b00:36\u000b00:37\u000b00:38\u000b00:39\u000b00:40\u000b00:41\u000b00:42\u000b00:43\u000b00:44\u000b00:45\u000b00:46\u000b00:47\u000b00:48\u000b00:49\u000b00:50\u000b00:51\u000b00:52\u000b00:53\u000b00:54\u000b00:55\u000b00:56\u000b00:57\u000b00:58\u000b00:59\u000b01:00\u000b01:01\u000b01:02\u000b01:03\u000b01:04\u000b01:05\u000b01:06\u000b01:07\u000b01:08\u000b01:09\u000b01:10\u000b01:11\u000b01:12\u000b01:13\u000b01:14\u000b01:15\u000b01:16\u000b01:17\u000b01:18\u000b01:19\u000b01:20\u000b01:21\u000b01:22\u000b01:23\u000b01:24\u000b01:25\u000b01:26\u000b01:27\u000b01:28\u000b01:29\u000b01:30\u000b01:31\u000b01:32\u000b01:33\u000b01:34\u000b01:35\u000b01:36\u000b01:37\u000b01:38\u000b01:39\u000b01:40\u000b01:41\u000b01:42\u000b01:43\u000b01:44\u000b01:45\u000b01:46\u000b01:47\u000b01:48\u000b01:49\u000b01:50\u000b01:51\u000b01:52\u000b01:53\u000b01:54\u000b01:55\u000b01:56\u000b01:57\u000b01:58\u000b01:59\u000b02:00\u000b02:01\u000b02:02\u000b02:03\u000b02:04\u000b02:05\u000b02:06\u000b02:07\u000b02:08\u000b02:09\u000b02:10\u000b02:11\u000b02:12\u000b02:13\u000b02:14\u000b02:15\u000b02:16\u000b02:17\u000b02:18\u000b02:19\u000b02:20\u000b02:21\u000b02:22\u000b02:23\u000b02:24\u000b02:25\u000b02:26\u000b02:27\u000b02:28\u000b02:29\u000b02:30\u000b02:31\u000b02:32\u000b02:33\u000b02:34\u000b02:35\u000b02:36\u000b02:37\u000b02:38\u000b02:39\u000b02:40\u000b02:41\u000b02:42\u000b02:43\u000b02:44\u000b02:45\u000b02:46\u000b02:47\u000b02:48\u000b02:49\u000b02:50\u000b02:51\u000b02:52\u000b02:53\u000b02:54\u000b02:55\u000b02:56\u000b02:57\u000b02:58\u000b02:59\u000b03:00\u000b03:01\u000b03:02\u000b03:03\u000b03:04\u000b03:05\u000b03:06\u000b03:07\u000b03:08\u000b03:09\u000b03:10\u000b03:11\u000b03:12\u000b03:13\u000b03:14\u000b03:15\u000b03:16\u000b03:17\u000b03:18\u000b03:19\u000b03:20\u000b03:21\u000b03:22\u000b03:23\u000b03:24\u000b03:25\u000b03:26\u000b03:27\u000b03:28\u000b03:29\u000b03:30\u000b03:31\u000b03:32\u000b03:33\u000b03:34\u000b03:35\u000b03:36\u000b03:37\u000b03:38\u000b03:39\u000b03:40\u000b03:41\u000b03:42\u000b03:43\u000b03:44\u000b03:45\u000b03:46\u000b03:47\u000b03:48\u000b03:49\u000b03:50\u000b03:51\u000b03:52\u000b03:53\u000b03:54\u000b03:55\u000b03:56\u000b03:57\u000b03:58\u000b03:59\u000b04:00\u000b04:01\u000b04:02\u000b04:03\u000b04:04\u000b04:05\u000b04:06\u000b04:07\u000b04:08\u000b04:09\u000b04:10\u000b04:11\u000b04:12\u000b04:13\u000b04:14\u000b04:15\u000b04:16\u000b04:17\u000b04:18\u000b04:19\u000b04:20\u000b04:21\u000b04:22\u000b04:23\u000b04:24\u000b04:25\u000b04:26\u000b04:27\u000b04:28\u000b04:29\u000b04:30\u000b04:31\u000b04:32\u000b04:33\u000b04:34\u000b04:35\u000b04:36\u000b04:37\u000b04:38\u000b04:39\u000b04:40\u000b04:41\u000b04:42\u000b04:43\u000b04:44\u000b04:45\u000b04:46\u000b04:47\u000b04:48\u000b04:49\u000b04:50\u000b04:51\u000b04:52\u000b04:53\u000b04:54\u000b04:55\u000b04:56\u000b04:57\u000b04:58\u000b04:59\u000b05:00\u000b05:01\u000b05:02\u000b05:03\u000b05:04\u000b05:05\u000b05:06\u000b05:07\u000b05:08\u000b05:09\u000b05:10\u000b05:11\u000b05:12\u000b05:13\u000b05:14\u000b05:15\u000b05:16\u000b05:17\u000b05:18\u000b05:19\u000b05:20\u000b05:21\u000b05:22\u000b05:23\u000b05:24\u000b05:25\u000b05:26\u000b05:27\u000b05:28\u000b05:29\u000b05:30\u000b05:31\u000b05:32\u000b05:33\u000b05:34\u000b05:35\u000b05:36\u000b05:37\u000b05:38\u000b05:39\u000b05:40\u000b05:41\u000b05:42\u000b05:43\u000b05:44\u000b05:45\u000b05:46\u000b05:47\u000b05:48\u000b05:49\u000b05:50\u000b05:51\u000b05:52\u000b05:53\u000b05:54\u000b05:55\u000b05:56\u000b05:57\u000b05:58\u000b05:59\u000b06:00\u000b06:01\u000b06:02\u000b06:03\u000b06:04\u000b06:05\u000b06:06\u000b06:07\u000b06:08\u000b06:09\u000b06:10\u000b06:11\u000b06:12\u000b06:13\u000b06:14\u000b06:15\u000b06:16\u000b06:17\u000b06:18\u000b06:19\u000b06:20\u000b06:21\u000b06:22\u000b06:23\u000b06:24\u000b06:25\u000b06:26\u000b06:27\u000b06:28\u000b06:29\u000b06:30\u000b06:31\u000b06:32\u000b06:33\u000b06:34\u000b06:35\u000b06:36\u000b06:37\u000b06:38\u000b06:39\u000b06:40\u000b06:41\u000b06:42\u000b06:43\u000b06:44\u000b06:45\u000b06:46\u000b06:47\u000b06:48\u000b06:49\u000b06:50\u000b06:51\u000b06:52\u000b06:53\u000b06:54\u000b06:55\u000b06:56\u000b06:57\u000b06:58\u000b06:59\u000b07:00\u000b07:01\u000b07:02\u000b07:03\u000b07:04\u000b07:05\u000b07:06\u000b07:07\u000b07:08\u000b07:09\u000b07:10\u000b07:11\u000b07:12\u000b07:13\u000b07:14\u000b07:15\u000b07:16\u000b07:17\u000b07:18\u000b07:19\u000b07:20\u000b07:21\u000b07:22\u000b07:23\u000b07:24\u000b07:25\u000b07:26\u000b07:27\u000b07:28\u000b07:29\u000b07:30\u000b07:31\u000b07:32\u000b07:33\u000b07:34\u000b07:35\u000b07:36\u000b07:37\u000b07:38\u000b07:39\u000b07:40\u000b07:41\u000b07:42\u000b07:43\u000b07:44\u000b07:45\u000b07:46\u000b07:47\u000b07:48\u000b07:49\u000b07:50\u000b07:51\u000b07:52\u000b07:53\u000b07:54\u000b07:55\u000b07:56\u000b07:57\u000b07:58\u000b07:59\u000b08:00\u000b08:01\u000b08:02\u000b08:03\u000b08:04\u000b08:05\u000b08:06\u000b08:07\u000b08:08\u000b08:09\u000b08:10\u000b08:11\u000b08:12\u000b08:13\u000b08:14\u000b08:15\u000b08:16\u000b08:17\u000b08:18\u000b08:19\u000b08:20\u000b08:21\u000b08:22\u000b08:23\u000b08:24\u000b08:25\u000b08:26\u000b08:27\u000b08:28\u000b08:29\u000b08:30\u000b08:31\u000b08:32\u000b08:33\u000b08:34\u000b08:35\u000b08:36\u000b08:37\u000b08:38\u000b08:39\u000b08:40\u000b08:41\u000b08:42\u000b08:43\u000b08:44\u000b08:45\u000b08:46\u000b08:47\u000b08:48\u000b08:49\u000b08:50\u000b08:51\u000b08:52\u000b08:53\u000b08:54\u000b08:55\u000b08:56\u000b08:57\u000b08:58\u000b08:59\u000b09:00\u000b09:01\u000b09:02\u000b09:03\u000b09:04\u000b09:05\u000b09:06\u000b09:07\u000b09:08\u000b09:09\u000b09:10\u000b09:11\u000b09:12\u000b09:13\u000b09:14\u000b09:15\u000b09:16\u000b09:17\u000b09:18\u000b09:19\u000b09:20\u000b09:21\u000b09:22\u000b09:23\u000b09:24\u000b09:25\u000b09:26\u000b09:27\u000b09:28\u000b09:29\u000b09:30\u000b09:31\u000b09:32\u000b09:33\u000b09:34\u000b09:35\u000b09:36\u000b09:37\u000b09:38\u000b09:39\u000b09:40\u000b09:41\u000b09:42\u000b09:43\u000b09:44\u000b09:45\u000b09:46\u000b09:47\u000b09:48\u000b09:49\u000b09:50\u000b09:51\u000b09:52\u000b09:53\u000b09:54\u000b09:55\u000b09:56\u000b09:57\u000b09:58\u000b09:59\u000b10:00\u000b10:01\u000b10:02\u000b10:03\u000b10:04\u000b10:05\u000b10:06\u000b10:07\u000b10:08\u000b10:09\u000b10:10\u000b10:11\u000b10:12\u000b10:13\u000b10:14\u000b10:15\u000b10:16\u000b10:17\u000b10:18\u000b10:19\u000b10:20\u000b10:21\u000b10:22\u000b10:23\u000b10:24\u000b10:25\u000b10:26\u000b10:27\u000b10:28\u000b10:29\u000b10:30\u000b10:31\u000b10:32\u000b10:33\u000b10:34\u000b10:35\u000b10:36\u000b10:37\u000b10:38\u000b10:39\u000b10:40\u000b10:41\u000b10:42\u000b10:43\u000b10:44\u000b10:45\u000b10:46\u000b10:47\u000b10:48\u000b10:49\u000b10:50\u000b10:51\u000b10:52\u000b10:53\u000b10:54\u000b10:55\u000b10:56\u000b10:57\u000b10:58\u000b10:59\u000b11:00\u000b11:01\u000b11:02\u000b11:03\u000b11:04\u000b11:05\u000b11:06\u000b11:07\u000b11:08\u000b11:09\u000b11:10\u000b11:11\u000b11:12\u000b11:13\u000b11:14\u000b11:15\u000b11:16\u000b11:17\u000b11:18\u000b11:19\u000b11:20\u000b11:21\u000b11:22\u000b11:23\u000b11:24\u000b11:25\u000b11:26\u000b11:27\u000b11:28\u000b11:29\u000b11:30\u000b11:31\u000b11:32\u000b11:33\u000b11:34\u000b11:35\u000b11:36\u000b11:37\u000b11:38\u000b11:39\u000b11:40\u000b11:41\u000b11:42\u000b11:43\u000b11:44\u000b11:45\u000b11:46\u000b11:47\u000b11:48\u000b11:49\u000b11:50\u000b11:51\u000b11:52\u000b11:53\u000b11:54\u000b11:55\u000b11:56\u000b11:57\u000b11:58\u000b11:59\u000b12:00\u000b12:01\u000b12:02\u000b12:03\u000b12:04\u000b12:05\u000b12:06\u000b12:07\u000b12:08\u000b12:09\u000b12:10\u000b12:11\u000b12:12\u000b12:13\u000b12:14\u000b12:15\u000b12:16\u000b12:17\u000b12:18\u000b12:19\u000b12:20\u000b12:21\u000b12:22\u000b12:23\u000b12:24\u000b12:25\u000b12:26\u000b12:27\u000b12:28\u000b12:29\u000b12:30\u000b12:31\u000b12:32\u000b12:33\u000b12:34\u000b12:35\u000b12:36\u000b12:37\u000b12:38\u000b12:39\u000b12:40\u000b12:41\u000b12:42\u000b12:43\u000b12:44\u000b12:45\u000b12:46\u000b12:47\u000b12:48\u000b12:49\u000b12:50\u000b12:51\u000b12:52\u000b12:53\u000b12:54\u000b12:55\u000b12:56\u000b12:57\u000b12:58\u000b12:59\u000b13:00\u000b13:01\u000b13:02\u000b13:03\u000b13:04\u000b13:05\u000b13:06\u000b13:07\u000b13:08\u000b13:09\u000b13:10\u000b13:11\u000b13:12\u000b13:13\u000b13:14\u000b13:15\u000b13:16\u000b13:17\u000b13:18\u000b13:19\u000b13:20\u000b13:21\u000b13:22\u000b13:23\u000b13:24\u000b13:25\u000b13:26\u000b13:27\u000b13:28\u000b13:29\u000b13:30\u000b13:31\u000b13:32\u000b13:33\u000b13:34\u000b13:35\u000b13:36\u000b13:37\u000b13:38\u000b13:39\u000b13:40\u000b13:41\u000b13:42\u000b13:43\u000b13:44\u000b13:45\u000b13:46\u000b13:47\u000b13:48\u000b13:49\u000b13:50\u000b13:51\u000b13:52\u000b13:53\u000b13:54\u000b13:55\u000b13:56\u000b13:57\u000b13:58\u000b13:59\u000b14:00\u000b14:01\u000b14:02\u000b14:03\u000b14:04\u000b14:05\u000b14:06\u000b14:07\u000b14:08\u000b14:09\u000b14:10\u000b14:11\u000b14:12\u000b14:13\u000b14:14\u000b14:15\u000b14:16\u000b14:17\u000b14:18\u000b14:19\u000b14:20\u000b14:21\u000b14:22\u000b14:23\u000b14:24\u000b14:25\u000b14:26\u000b14:27\u000b14:28\u000b14:29\u000b14:30\u000b14:31\u000b14:32\u000b14:33\u000b14:34\u000b14:35\u000b14:36\u000b14:37\u000b14:38\u000b14:39\u000b14:40\u000b14:41\u000b14:42\u000b14:43\u000b14:44\u000b14:45\u000b14:46\u000b14:47\u000b14:48\u000b14:49\u000b14:50\u000b14:51\u000b14:52\u000b14:53\u000b14:54\u000b14:55\u000b14:56\u000b14:57\u000b14:58\u000b14:59\u000b15:00\u000b15:01\u000b15:02\u000b15:03\u000b15:04\u000b15:05\u000b15:06\u000b15:07\u000b15:08\u000b15:09\u000b15:10\u000b15:11\u000b15:12\u000b15:13\u000b15:14\u000b15:15\u000b15:16\u000b15:17\u000b15:18\u000b15:19\u000b15:20\u000b15:21\u000b15:22\u000b15:23\u000b15:24\u000b15:25\u000b15:26\u000b15:27\u000b15:28\u000b15:29\u000b15:30\u000b15:31\u000b15:32\u000b15:33\u000b15:34\u000b15:35\u000b15:36\u000b15:37\u000b15:38\u000b15:39\u000b15:40\u000b15:41\u000b15:42\u000b15:43\u000b15:44\u000b15:45\u000b15:46\u000b15:47\u000b15:48\u000b15:49\u000b15:50\u000b15:51\u000b15:52\u000b15:53\u000b15:54\u000b15:55\u000b15:56\u000b15:57\u000b15:58\u000b15:59\u000b16:00\u000b16:01\u000b16:02\u000b16:03\u000b16:04\u000b16:05\u000b16:06\u000b16:07\u000b16:08\u000b16:09\u000b16:10\u000b16:11\u000b16:12\u000b16:13\u000b16:14\u000b16:15\u000b16:16\u000b16:17\u000b16:18\u000b16:19\u000b16:20\u000b16:21\u000b16:22\u000b16:23\u000b16:24\u000b16:25\u000b16:26\u000b16:27\u000b16:28\u000b16:29\u000b16:30\u000b16:31\u000b16:32\u000b16:33\u000b16:34\u000b16:35\u000b16:36\u000b16:37\u000b16:38\u000b16:39\u000b16:40\u000b16:41\u000b16:42\u000b16:43\u000b16:44\u000b16:45\u000b16:46\u000b16:47\u000b16:48\u000b16:49\u000b16:50\u000b16:51\u000b16:52\u000b16:53\u000b16:54\u000b16:55\u000b16:56\u000b16:57\u000b16:58\u000b16:59\u000b17:00\u000b17:01\u000b17:02\u000b17:03\u000b17:04\u000b17:05\u000b17:06\u000b17:07\u000b17:08\u000b17:09\u000b17:10\u000b17:11\u000b17:12\u000b17:13\u000b17:14\u000b17:15\u000b17:16\u000b17:17\u000b17:18\u000b17:19\u000b17:20\u000b17:21\u000b17:22\u000b17:23\u000b17:24\u000b17:25\u000b17:26\u000b17:27\u000b17:28\u000b17:29\u000b17:30\u000b17:31\u000b17:32\u000b17:33\u000b17:34\u000b17:35\u000b17:36\u000b17:37\u000b17:38\u000b17:39\u000b17:40\u000b17:41\u000b17:42\u000b17:43\u000b17:44\u000b17:45\u000b17:46\u000b17:47\u000b17:48\u000b17:49\u000b17:50\u000b17:51\u000b17:52\u000b17:53\u000b17:54\u000b17:55\u000b17:56\u000b17:57\u000b17:58\u000b17:59\u000b18:00\u000b18:01\u000b18:02\u000b18:03\u000b18:04\u000b18:05\u000b18:06\u000b18:07\u000b18:08\u000b18:09\u000b18:10\u000b18:11\u000b18:12\u000b18:13\u000b18:14\u000b18:15\u000b18:16\u000b18:17\u000b18:18\u000b18:19\u000b18:20\u000b18:21\u000b18:22\u000b18:23\u000b18:24\u000b18:25\u000b18:26\u000b18:27\u000b18:28\u000b18:29\u000b18:30\u000b18:31\u000b18:32\u000b18:33\u000b18:34\u000b18:35\u000b18:36\u000b18:37\u000b18:38\u000b18:39\u000b18:40\u000b18:41\u000b18:42\u000b18:43\u000b18:44\u000b18:45\u000b18:46\u000b18:47\u000b18:48\u000b18:49\u000b18:50\u000b18:51\u000b18:52\u000b18:53\u000b18:54\u000b18:55\u000b18:56\u000b18:57\u000b18:58\u000b18:59\u000b19:00\u000b19:01\u000b19:02\u000b19:03\u000b19:04\u000b19:05\u000b19:06\u000b19:07\u000b19:08\u000b19:09\u000b19:10\u000b19:11\u000b19:12\u000b19:13\u000b19:14\u000b19:15\u000b19:16\u000b19:17\u000b19:18\u000b19:19\u000b19:20\u000b19:21\u000b19:22\u000b19:23\u000b19:24\u000b19:25\u000b19:26\u000b19:27\u000b19:28\u000b19:29\u000b19:30\u000b19:31\u000b19:32\u000b19:33\u000b19:34\u000b19:35\u000b19:36\u000b19:37\u000b19:38\u000b19:39\u000b19:40\u000b19:41\u000b19:42\u000b19:43\u000b19:44\u000b19:45\u000b19:46\u000b19:47\u000b19:48\u000b19:49\u000b19:50\u000b19:51\u000b19:52\u000b19:53\u000b19:54\u000b19:55\u000b19:56\u000b19:57\u000b19:58\u000b19:59\u000b20:00\u000b20:01\u000b20:02\u000b20:03\u000b20:04\u000b20:05\u000b20:06\u000b20:07\u000b20:08\u000b20:09\u000b20:10\u000b20:11\u000b20:12\u000b20:13\u000b20:14\u000b20:15\u000b20:16\u000b20:17\u000b20:18\u000b20:19\u000b20:20\u000b20:21\u000b20:22\u000b20:23\u000b20:24\u000b20:25\u000b20:26\u000b20:27\u000b20:28\u000b20:29\u000b20:30\u000b20:31\u000b20:32\u000b20:33\u000b20:34\u000b20:35\u000b20:36\u000b20:37\u000b20:38\u000b20:39\u000b20:40\u000b20:41\u000b20:42\u000b20:43\u000b20:44\u000b20:45\u000b20:46\u000b20:47\u000b20:48\u000b20:49\u000b20:50\u000b20:51\u000b20:52\u000b20:53\u000b20:54\u000b20:55\u000b20:56\u000b20:57\u000b20:58\u000b20:59\u000b21:00\u000b21:01\u000b21:02\u000b21:03\u000b21:04\u000b21:05\u000b21:06\u000b21:07\u000b21:08\u000b21:09\u000b21:10\u000b21:11\u000b21:12\u000b21:13\u000b21:14\u000b21:15\u000b21:16\u000b21:17\u000b21:18\u000b21:19\u000b21:20\u000b21:21\u000b21:22\u000b21:23\u000b21:24\u000b21:25\u000b21:26\u000b21:27\u000b21:28\u000b21:29\u000b21:30\u000b21:31\u000b21:32\u000b21:33\u000b21:34\u000b21:35\u000b21:36\u000b21:37\u000b21:38\u000b21:39\u000b21:40\u000b21:41\u000b21:42\u000b21:43\u000b21:44\u000b21:45\u000b21:46\u000b21:47\u000b21:48\u000b21:49\u000b21:50\u000b21:51\u000b21:52\u000b21:53\u000b21:54\u000b21:55\u000b21:56\u000b21:57\u000b21:58\u000b21:59\u000b22:00\u000b22:01\u000b22:02\u000b22:03\u000b22:04\u000b22:05\u000b22:06\u000b22:07\u000b22:08\u000b22:09\u000b22:10\u000b22:11\u000b22:12\u000b22:13\u000b22:14\u000b22:15\u000b22:16\u000b22:17\u000b22:18\u000b22:19\u000b22:20\u000b22:21\u000b22:22\u000b22:23\u000b22:24\u000b22:25\u000b22:26\u000b22:27\u000b22:28\u000b22:29\u000b22:30\u000b22:31\u000b22:32\u000b22:33\u000b22:34\u000b22:35\u000b22:36\u000b22:37\u000b22:38\u000b22:39\u000b22:40\u000b22:41\u000b22:42\u000b22:43\u000b22:44\u000b22:45\u000b22:46\u000b22:47\u000b22:48\u000b22:49\u000b22:50\u000b22:51\u000b22:52\u000b22:53\u000b22:54\u000b22:55\u000b22:56\u000b22:57\u000b22:58\u000b22:59\u000b23:00\u000b23:01\u000b23:02\u000b23:03\u000b23:04\u000b23:05\u000b23:06\u000b23:07\u000b23:08\u000b23:09\u000b23:10\u000b23:11\u000b23:12\u000b23:13\u000b23:14\u000b23:15\u000b23:16\u000b23:17\u000b23:18\u000b23:19\u000b23:20\u000b23:21\u000b23:22\u000b23:23\u000b23:24\u000b23:25\u000b23:26\u000b23:27\u000b23:28\u000b23:29\u000b23:30\u000b23:31\u000b23:32\u000b23:33\u000b23:34\u000b23:35\u000b23:36\u000b23:37\u000b23:38\u000b23:39\u000b23:40\u000b23:41\u000b23:42\u000b23:43\u000b23:44\u000b23:45\u000b23:46\u000b23:47\u000b23:48\u000b23:49\u000b23:50\u000b23:51\u000b23:52\u000b23:53\u000b23:54\u000b23:55\u000b23:56\u000b23:57\u000b23:58\u000b23:59
prefer_tag=0
version=1
```

**Comment by dbohdan** [comment] 2024-06-10 08:44
> `C:\Temp\initool replace test>initool.exe replace test.ini #3 enabled 1 5` ...
the entire content of test.ini will outputted

I would like to see this output. It looks like you pasted the output of `initool.exe get test.ini #3` twice. 

I still cannot reproduce the bug. Could you extract [`long-ini.zip`](https://github.com/user-attachments/files/15759275/long-ini.zip) to the directory with `initool.exe`, run `replace.cmd`, and upload `updated-long.ini`?

**Comment by PeterCodar** [comment] 2024-06-10 08:55
[updated-long.zip](https://github.com/user-attachments/files/15759385/updated-long.zip)

Just as a side note:
The `long.ini` has Unix (LF) and the resulted `updated-long.ini` has Windows (CR LF)

**Comment by PeterCodar** [comment] 2024-06-10 09:10
What I found in my own tests (thanks to your idea to write a new ini):
If I redirect the output into a new INI, the value will be replaced as expected.

But it seems, that the value can't be replaced in the original INI itself.

What could be the cause for this?

**Comment by dbohdan** [comment] 2024-06-10 09:25
Okay, thanks.

> What could be the cause for this?

That's how initool works. It doesn't modify the original file.

Have you read the readme? This is an honest question. Feel free to answer "no" if you haven't. If you have and you didn't realize this, I probably need to emphasize it more.

**Comment by PeterCodar** [comment] 2024-06-10 09:37
I could not find an example for the new added replace function and wrongly assumed that a replace would exactly do that: "replace" the old value with the new value in the original file without creating a new file.

Sorry for that wrong assumption.

Maybe it will help if you clarify that fact with a replace example showing that in any case a new INI file will be written.
This new file must be used to overwrite the existing/old INI file with an additional command.

**Comment by dbohdan** [comment] 2024-06-11 07:58
I see. Thanks for explaining. I have updated the documentation to add [examples for `replace`](https://github.com/dbohdan/initool/blob/fc0c3b1314155781e8fad8a8864073355d4ecfad/README.md#replacing-text-in-a-value) and mentioned that initool never changes the input file.

[v0.18.0](https://github.com/dbohdan/initool/releases/tag/v0.18.0) is now released. I am closing this issue as completed.

**Closed as completed by dbohdan** 2024-06-11 07:58 UTC
Labels: enhancement
